env: order-dev5
spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/baidu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order
server:
  port: 8082
PRODUCT:
  ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
rabbitmq:
  host: 192.168.1.104
  username: guest
  password: guest
  port: 5672
