env: product
spring:
  application:
    name: product

  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/baidu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8084
rabbitmq:
    host: 192.168.1.104
    username: guest
    password: guest
    port: 5672
